[username]
show_always = true
format = "[${user}](fg:#83a598) "

[hostname]
# ssh_only = false
format = "[@](fg:#657b83)[${hostname}](fg:#83a598) "

[line_break]
disabled = true

[c]
symbol = "î˜ "
style = "fg:#A8B9CC"

[conda]
symbol = "ï„Œ "
style = "fg:#83a598"

[directory]
read_only = " ó°Œ¾"
style = "fg:#689d6a"
truncation_length = 4


[docker_context]
symbol = "ïŒˆ "
style = "fg:#0db7ed"

[python]
symbol = "îˆµ "
style = "fg:#3776AB"

[golang]
symbol = "î˜§ "
style = "fg:#00ADD8"

[java]
symbol = "î‰– "
style = "fg:#007396"

[lua]
symbol = "î˜  "
style = "fg:#000080"

[memory_usage]
symbol = "ó°› "
style = "fg:#d3869b"

[nodejs]
symbol = "îœ˜ "
style = "fg:#8CC84B"

[rust]
symbol = "î¨ "
style = "fg:#B7410E"

[git_branch]
symbol = "ï˜ "
style = "fg:#79740e"

[git_status]
#symbol = "ï„Œ "
style = "fg:#98971a"

[env_var]
variable = "PYTHON_ENV"
symbol = "ğŸ="
style = "fg:#928374"

[cmd_duration]
min_time = 2000
style = "fg:#bdae93"

[character]
success_symbol = "[â¯](fg:#83a598)" # This changes the symbol and its color when the last command was successful
error_symbol = "[â¯](fg:#fb4934)"   # Optional: This changes the symbol and its color when the last command had an error. Adjust the color if needed.
